CREATE DATABASE IF NOT EXISTS `CA_Tech_Dojo` DEFAULT CHARACTER SET utf8mb4 ;
USE `CA_Tech_Dojo` ;

SET CHARSET utf8mb4;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(128) NOT NULL COMMENT '名前',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'ユーザ';

CREATE TABLE IF NOT EXISTS `game_settings` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `gacha_coin_consumption` INT NOT NULL COMMENT 'ガチャ1回あたりのコイン消費量',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ゲーム設定情報';
